"use client"

import { Montserrat, Poppins } from 'next/font/google'
import './globals.css'
// import { ThemeProvider } from "@material-tailwind/react"
import { ThemeProvider } from "next-themes";
import Navbar from './components/Navbar';

const montserrat = Montserrat({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ["400", "700"] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <ThemeProvider attribute="class">
      <Navbar/>
        {children}

      </ThemeProvider>
      </body>
    </html>
  )
}
