"use client"

import { Montserrat, Poppins } from 'next/font/google'
import './globals.css'
// import { ThemeProvider } from "@material-tailwind/react"
import { ThemeProvider } from "next-themes";
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const montserrat = Montserrat({ subsets: ['latin'], variable: '--font-montserrat' })
const poppins = Poppins({ subsets: ['latin'], weight: ["400", "700"], variable: '--font-poppins' })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <style jsx global>{`
        :root {
          --font-montserrat: ${montserrat.style.fontFamily};
          --font-poppins: ${poppins.style.fontFamily};
        }
        .montserrat {
          font-family: var(--font-montserrat);
        }

        .poppins {
          font-family: var(--font-poppins);
        }
      `}</style>
      <body className={poppins.className}>
      <ThemeProvider attribute="class">
      <Navbar/>
        {children}
      <Footer/>
      </ThemeProvider>
      </body>
    </html>
  )
}
